spring.application.name=secure-ai-gateway-backend

server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/secure-gateway

security.jwt.secret=THIS_IS_A_DEMO_SECRET_KEY_CHANGE_IT_1234567890
security.jwt.expiration-ms=3600000

logging.level.org.springframework.security=INFO




# ==== OpenAI Threat Detection ====
openai.api.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-4.1-mini
openai.api.key=${OPENAI_API_KEY: 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}
